#[[redirects]]
#  from = "https://mobx.netlify.com/*"
#  to = "https://mobx.pub/:splat"
#  status = 301
#  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false